name: Docker Image CI

on:
  push:
    branches: [ issue-162 ]


jobs:

  buildx:
    name: Build and push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Docker login
      run: >-
        echo "${{ secrets.GITHUB_TOKEN }}"
        | docker login -u "${{ github.actor }}" --password-stdin ghcr.io

    - name: Build flame
      run: | 
        docker build -f Dockerfile . \
        --platform linux/arm/v7 \
        --tag ghcr.io/$GITHUB_ACTOR/flame:armv7-$GITHUB_RUN_ID --push

      
